
import React from 'react';
import { Shield, FileSignature, Lock, Database, X } from './icons';
import Button from './Button';

export type LegalDocType = 'privacy' | 'tos' | 'gdpr' | 'cookies';

interface LegalModalProps {
  type: LegalDocType | null;
  onClose: () => void;
}

const LegalModal: React.FC<LegalModalProps> = ({ type, onClose }) => {
  if (!type) return null;

  const ownerData = {
    name: "Kamil Skomra",
    company: "HardbanRecords Lab",
    email: "hardbanrecordslab.pl@gmail.com"
  };

  const renderContent = () => {
    switch (type) {
      case 'privacy':
        return (
          <div className="space-y-4 text-sm text-slate-600 dark:text-slate-300">
            <h3 className="text-lg font-bold text-light-text dark:text-dark-text mb-2">1. Introduction</h3>
            <p>Welcome to Music Metadata Engine. We respect your privacy and are committed to protecting your personal data. This privacy policy will inform you as to how we look after your personal data when you visit our website and tell you about your privacy rights and how the law protects you.</p>
            
            <h3 className="text-lg font-bold text-light-text dark:text-dark-text mb-2">2. Data Controller</h3>
            <p>The controller for your personal data is:<br/>
            <strong>{ownerData.company} ({ownerData.name})</strong><br/>
            Contact: <a href={`mailto:${ownerData.email}`} className="text-accent-violet hover:underline">{ownerData.email}</a></p>

            <h3 className="text-lg font-bold text-light-text dark:text-dark-text mb-2">3. How We Collect Data</h3>
            <p><strong>Direct Interactions:</strong> Most of the processing in Music Metadata Engine happens <strong>client-side</strong> (in your browser). We do not upload your audio files to our permanent servers. However, during the analysis process, data snippets are sent to third-party APIs (Google Gemini, ACRCloud, MusicBrainz) to generate metadata.</p>
            
            <h3 className="text-lg font-bold text-light-text dark:text-dark-text mb-2">4. Third-Party Services</h3>
            <p>We use the following third-party services which may process data:</p>
            <ul className="list-disc pl-5">
                <li><strong>Google Gemini API:</strong> For AI analysis and content generation.</li>
                <li><strong>ACRCloud:</strong> For audio fingerprinting and recognition.</li>
                <li><strong>MusicBrainz:</strong> For metadata lookup.</li>
            </ul>
          </div>
        );
      case 'tos':
        return (
          <div className="space-y-4 text-sm text-slate-600 dark:text-slate-300">
            <h3 className="text-lg font-bold text-light-text dark:text-dark-text mb-2">1. Acceptance of Terms</h3>
            <p>By accessing and using the Music Metadata Engine ("Service"), provided by {ownerData.company} ("we," "us," or "our"), you accept and agree to be bound by the terms and provision of this agreement.</p>

            <h3 className="text-lg font-bold text-light-text dark:text-dark-text mb-2">2. Use of the Service</h3>
            <p>You agree to use the Service only for lawful purposes. You are responsible for all content (audio files) you analyze using our Service. You retain all ownership rights to your music.</p>

            <h3 className="text-lg font-bold text-light-text dark:text-dark-text mb-2">3. Intellectual Property</h3>
            <p>The Service and its original content (excluding content provided by users), features, and functionality are and will remain the exclusive property of {ownerData.company}.</p>

            <h3 className="text-lg font-bold text-light-text dark:text-dark-text mb-2">4. Disclaimer</h3>
            <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We do not warrant that the results generated by the AI (metadata, descriptions, etc.) will be 100% accurate or error-free.</p>
            
            <h3 className="text-lg font-bold text-light-text dark:text-dark-text mb-2">5. Limitation of Liability</h3>
            <p>In no event shall {ownerData.company}, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages.</p>
          </div>
        );
      case 'gdpr':
        return (
          <div className="space-y-4 text-sm text-slate-600 dark:text-slate-300">
            <p>We are committed to ensuring that your privacy is protected in accordance with the General Data Protection Regulation (GDPR).</p>

            <h3 className="text-lg font-bold text-light-text dark:text-dark-text mb-2">1. Your Rights</h3>
            <p>Under the GDPR, you have the following rights:</p>
            <ul className="list-disc pl-5">
                <li><strong>The right to access:</strong> You have the right to request copies of your personal data.</li>
                <li><strong>The right to rectification:</strong> You have the right to request that we correct any information you believe is inaccurate.</li>
                <li><strong>The right to erasure:</strong> You have the right to request that we erase your personal data.</li>
            </ul>

            <h3 className="text-lg font-bold text-light-text dark:text-dark-text mb-2">2. Data Processing</h3>
            <p>We process data based on your consent (when you upload a file) and legitimate interest (to provide the service). Since we operate mainly client-side, we store minimal data on our servers. Local Storage is used on your device to save history and preferences.</p>

            <h3 className="text-lg font-bold text-light-text dark:text-dark-text mb-2">3. Contact for GDPR Inquiries</h3>
            <p>If you wish to exercise any of these rights, please contact us at: <br/>
            Email: <a href={`mailto:${ownerData.email}`} className="text-accent-violet hover:underline">{ownerData.email}</a></p>
          </div>
        );
      case 'cookies':
        return (
           <div className="space-y-4 text-sm text-slate-600 dark:text-slate-300">
            <h3 className="text-lg font-bold text-light-text dark:text-dark-text mb-2">1. What are Cookies?</h3>
            <p>Cookies are text files placed on your computer to collect standard Internet log information and visitor behavior information. However, Music Metadata Engine primarily uses <strong>Local Storage</strong> rather than traditional tracking cookies.</p>

            <h3 className="text-lg font-bold text-light-text dark:text-dark-text mb-2">2. How we use Local Storage</h3>
            <p>We use Local Storage to improve your experience, including:</p>
            <ul className="list-disc pl-5">
                <li>Keeping you signed in (if applicable).</li>
                <li>Saving your analysis history locally on your device.</li>
                <li>Storing your preferences (e.g., Dark Mode, API Keys).</li>
            </ul>

            <h3 className="text-lg font-bold text-light-text dark:text-dark-text mb-2">3. Managing Cookies</h3>
            <p>You can set your browser not to accept cookies or to clear Local Storage. However, in a few cases, some of our website features (like saved history) may not function as a result.</p>
          </div>
        );
      default:
        return null;
    }
  };

  const titles: Record<LegalDocType, string> = {
      privacy: 'Privacy Policy',
      tos: 'Terms and Conditions',
      gdpr: 'GDPR Compliance',
      cookies: 'Cookie Policy'
  };

  const icons: Record<LegalDocType, React.ReactNode> = {
      privacy: <Lock className="w-6 h-6 text-white" />,
      tos: <FileSignature className="w-6 h-6 text-white" />,
      gdpr: <Shield className="w-6 h-6 text-white" />,
      cookies: <Database className="w-6 h-6 text-white" />
  };

  return (
    <div 
      className="fixed inset-0 bg-black/60 z-[60] flex items-center justify-center p-4 animate-fade-in"
      onClick={onClose}
    >
      <div 
        className="bg-light-card dark:bg-dark-card rounded-2xl shadow-xl w-full max-w-3xl border border-slate-200 dark:border-slate-800 relative overflow-hidden flex flex-col max-h-[85vh]"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="p-6 border-b border-slate-200 dark:border-slate-800 flex justify-between items-center bg-slate-50 dark:bg-slate-900/50">
             <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-gradient-to-br from-slate-500 to-slate-700 rounded-lg flex items-center justify-center shrink-0">
                    {icons[type]}
                </div>
                <div>
                    <h2 className="text-2xl font-bold text-light-text dark:text-dark-text tracking-tight">
                        {titles[type]}
                    </h2>
                    <p className="text-xs text-slate-500 dark:text-slate-400">Last updated: {new Date().toLocaleDateString()}</p>
                </div>
            </div>
            <button onClick={onClose} className="p-2 rounded-full hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors" aria-label="Close modal">
                <X className="w-6 h-6 text-slate-500" />
            </button>
        </div>
        
        {/* Content */}
        <div className="p-8 overflow-y-auto custom-scrollbar">
            {renderContent()}
            
            <div className="mt-8 pt-8 border-t border-slate-200 dark:border-slate-800 text-xs text-slate-400">
                Owner: {ownerData.company} | {ownerData.name} | {ownerData.email}
            </div>
        </div>

        {/* Footer Actions */}
        <div className="p-4 bg-slate-50 dark:bg-slate-900/50 border-t border-slate-200 dark:border-slate-800 flex justify-end">
            <Button onClick={onClose} variant="secondary">
                Close Document
            </Button>
        </div>
      </div>
    </div>
  );
};

export default LegalModal;
